import { Dimensions, Platform, StyleSheet } from "react-native";
import { theme } from "../../global/themes";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        paddingTop: Platform.OS === 'android' ? 30 : 0,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,   
        elevation: 5,
    },
    cabecalho: {
        width: '100%', 
        height: 200,
        justifyContent: "space-between",
        borderRadius: 10,
        padding: 0,
        paddingTop: Platform.OS === 'android' ? 40 : 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,   
        elevation: 5,
        backgroundColor: theme.colors.secundary,
    },
    boxLogo: {
        flex: 1,
        width: '100%',
        justifyContent: "space-between",
        alignItems: 'center',
        marginBottom: 20,
        
    },
    text: {
        fontSize: 16,
        color: theme.colors.black,
        textAlign: 'center',
        marginTop: -50,
        maxWidth: '90%',
        fontWeight: '500',
       
  },
     logo: {
        width: 120,
        height: 150,
        resizeMode: 'contain',
  },

  nome: { 
    fontSize: 25,
    fontWeight: '600',
    color: theme.colors.secundary,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    maxWidth: '100%',
    fontFamily: 'Aladin_400Regular',
  },
  buttonsContainer: {
    flex: 1,
    paddingHorizontal: 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center', 
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 20,
    gap: 1, 
  },
  button: {
    width: '45%',
    backgroundColor: '#fbffffff',
    paddingVertical: 20,
    marginBottom: 0, 
    marginHorizontal: 5, 
    borderWidth: 1,
    borderColor: theme.colors.secundary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000000ff",
    shadowOffset: {   width: 0, height: 2  },
    shadowOpacity: 5.25,
    shadowRadius: 4.84,
    elevation: 5,
  },
  certificadosButtonText: {
    color: '#000000ff',
    fontSize: 16, 
    fontWeight: 'bold',
  }, 
  cursosButtonText: {
    color: '#000000ff',
    fontSize: 16, 
    fontWeight: 'bold',
  },
  fundo: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 30 : 0, 
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.4, 
    zIndex: -1, 
  },

  welcome: {
    fontSize: 16,
    color: theme.colors.secundary,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    maxWidth: '100%',
    fontWeight: '600',
  
  },
    MeusCursos: {
    fontSize: 30,
    color: theme.colors.black,
    paddingHorizontal: 3,
    textAlign: 'left',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    maxWidth: '100%',
    fontWeight: '600',
    
  },
  cursosCard: {
    flex: 1,
    width: '100%',
    height: 500,
    paddingHorizontal: 0,
    bottom: 20,
    marginTop: 40,
    gap: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 13.84,   
    elevation: 5, 
    overflow: 'hidden', 
    borderColor: theme.colors.gray,
    borderWidth: 1,
  },

  cursoImage: {
    width: '100%', 
    height: '55%', 
    borderRadius: 30, 
    overflow: 'hidden', 
    marginTop: 0,
    borderEndEndRadius: 0,
    borderEndStartRadius: 0,
    borderColor: theme.colors.primary,
    borderWidth: 1,
    backgroundColor: '#ffffffff',
  },
  cursoTitle: {
    fontSize: 22,
    fontWeight: '500',
    marginTop: 20,
    color: theme.colors.white,
  },
  cursoDescription: {
    fontSize: 14,
    color: theme.colors.white,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  cursoTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '95%',
    marginTop: 0,
    paddingHorizontal: 10,
    paddingVertical: 5,
    
  },
  
  cursoLevel: {
    fontSize: 12,
    marginTop: 25,
    backgroundColor:'#04f60c74',
    borderRadius: 5,
    width: 60,
    height: '35%',
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 1)',
    fontWeight: '600',
    
  },
  cursoDuration: {
    fontSize: 15,
    color: theme.colors.white,
    fontWeight: '500',
    marginLeft: 0,
  },

  cursoInfo: {
    fontSize: 12,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 5, 
    justifyContent: 'space-between', 
    width: '100%',
    height: '15%',
  },
  cursoTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5, 
  },
  cursosUsers: {
    fontSize: 12,
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center', 
    paddingHorizontal: 0,
    gap: 5, 
    justifyContent: 'flex-end', 
    width: 'auto', 
  },
  inscricoes: {
    fontSize: 15,
    textAlign: 'left', 
    color: theme.colors.white, 
    fontWeight: '500',
    marginLeft: 0, 
  },

  cursoProgress: {
    width: '90%',
    backgroundColor: '#cacdcbff', 
    paddingVertical: 10,
    marginBottom: 10, 
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',

  },
  cursoProgressText: {
    fontSize: 15,
    textAlign: 'center', 
    color: theme.colors.black, 
    fontWeight: '500',
    marginLeft: 0, 
    
  },  
    cursoLevelJS: {
    fontSize: 12,
    marginTop: 25,
    backgroundColor:'#f2ff00b5',
    borderRadius: 5,
    width: 60,
    height: '35%',
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 1)',
    fontWeight: '600',
  },
});